packages:
  - 'apps/*'
  - 'packages/*'
overrides:
  typescript: '5.7.3'
allowBuilds:
  '@scarf/scarf': false
  argon2: true
  esbuild: true
  msgpackr-extract: true
  sharp: true
  puppeteer: true
  '@puppeteer/browsers': true
  stream-chat: true
